### ISSUE TITLE
iOS background app kill

### ISSUE THREAD

**Issue by akashish** [mnill/cordova-app-updater#12]
Get update from sever, perfect working in android but having issue with ios in iOS i have to kill the background app then it is updating the app .

In android it is working without killing background app.

**Comment by mnill** [comment]
iOS will be updated if app has been unload from memory. By my stats 99% users kills his basckground apps. 
Other way is redirect app to updater.html

**Comment by akashish** [comment]
Hi,

We want auto update to work in iOS without killing the app from background,
Is there a way to achieve this without redirecting to update.html once the
user is already within the app.

**Comment by mnill** [comment]
Can u please describe u vision of this process?
How it must look like? 
Even if you update files in background you still have old application loaded in webview. You need restart the app or refresh the page.

**Comment by mnill** [comment]
expired
