### ISSUE TITLE
Can't find server url error

### ISSUE THREAD

**Issue by khamaileon** [mnill/cordova-app-updater#7]
I've got this error on Cordova 6.1.1 with the following procedure:

There is config.xml for testing.
instruction:
cordova create test
cd test
cordova platform add ios
cordova plugin add https://github.com/mnill/cordova-app-updater

copy\paste my config

cordova run ios --device
[config.xml.zip](https://github.com/mnill/cordova-app-updater/files/264925/config.xml.zip)

**Comment by mnill** [comment]
I think you tried android, not ios?
I apply path on master, please try again.

**Comment by khamaileon** [comment]
Yes indeed.
Works like a charm! Thank you :+1:
