### ISSUE TITLE
Use of splashcreen

### ISSUE THREAD

**Issue by khamaileon** [mnill/cordova-app-updater#8]
I already use a splashcreen in my project that I'm hiding.

``` xml
<preference name="AutoHideSplashScreen" value="false" />
<preference name="FadeSplashScreenDuration" value="1000" />
<preference name="UpdaterPolicy" value="tryupdate" />
<preference name="UpdaterHideSplashScreen" value="false" />
```

``` javascript
platform.ready()
  .then(log.info('platform ready'))
  .then(() => this.getOrCreateUser(this))
  .then(() => this.getOrCreateDevice(this))
  .then(device => this.registerNotification(device))
  .then(() => navigator.splashscreen.hide());
```

I tried UpdaterHideSplashScreen = true but my splashcreen does not hide. With UpdaterHideSplashScreen = false, the hiding is not triggered by me. 
And I never saw the updating progress as mentioned in the documentation.

**Comment by mnill** [comment]
What you mean "And I never saw the updating progress as mentioned in the documentation." ? 
Visualization not realized yet

**Comment by mnill** [comment]
I will make some type of updating screen in near future.

**Comment by mnill** [comment]
About splash screen I don't clearly understood you, but I will test it tomorrow.

**Comment by khamaileon** [comment]
I would like the splash screen to be hidden by me and not by cordova-app-updater. With UpdaterHideSplashScreen at True, the splash screen never hides. WIth UpdaterHideSplashScreen at False, the splash is hidden at the end of the updating process and not when I ask for it.
Wouldn't it be better if the splash screen is no longer controlled by the plug-in ?

**Comment by mnill** [comment]
I think i repaired this issue, thanks for reporting.

I want to make 'updating in progress' page template in near future. For long updates. It is a reason to keep this parameter.

**Comment by khamaileon** [comment]
Thanks @mnill. It's OK now!
